### ISSUE TITLE
Stage 1 Checklist - do oceny

### ISSUE THREAD

**Issue by glapinski** [glapinski/concurrent-programming#4]
Project Stage 1 Checklist
- [x] text is in C# and use .NET
- [x] build succeeded
- [x] all UT are green
- [x] `Data` layer is clearly stated using language terms only (no database of file access is required)
- [x] `Data` API is abstract
- [x] `Logic` layer is clearly stated using language terms only
- [x] `Logic` API is clearly stated
- [x] `Logic` uses only the abstract `Data` layer API
- [x] `Presentation` layer is clearly stated using language terms only
- [x] mvvm and xaml is applied to implement GUI
- [ ] reactive and interactive user interaction for user (operator) communication
- [ ] reactive and interactive programming is used for layers communication
- [ ] Object model representing process data
- [ ] Unit Test - layers are tested independently using abstract API
- [ ] Dependency injection (additional framework is not required)
- [ ] Mock is used for testing purposes (expected but not required)
